In [2]:
import pandas as pd
bigmac = pd.read_csv("bigmac.csv",parse_dates=["Date"])
bigmac.head()

        Date    Country  Price in US Dollars
0 2016-01-01  Argentina                 2.39
1 2016-01-01  Australia                 3.74
2 2016-01-01     Brazil                 3.35
3 2016-01-01    Britain                 4.22
4 2016-01-01     Canada                 4.14

# set_index()

In [3]:
bigmac.set_index(keys = ["Date", "Country",],inplace=True)
bigmac.head()

                      Price in US Dollars
Date       Country
2016-01-01 Argentina                 2.39
           Australia                 3.74
           Brazil                    3.35
           Britain                   4.22
           Canada                    4.14

In [4]:
bigmac.sort_index(inplace = True)

In [5]:
bigmac.index.names

FrozenList(['Date', 'Country'])

In [6]:
type(bigmac.index)

pandas.indexes.multi.MultiIndex

In [7]:
bigmac.index[0]

(Timestamp('2010-01-01 00:00:00'), 'Argentina')

# .get_level_values

In [8]:
import pandas as pd
bigmac = pd.read_csv("bigmac.csv",parse_dates=["Date"],index_col = ["Date","Country"])
bigmac.sort_index(inplace = True)
bigmac.head()

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76
           Britain                   3.67
           Canada                    3.97

In [9]:
bigmac.index.get_level_values(0)
#bigmac.index.get_level_values("Date")

DatetimeIndex(['2010-01-01', '2010-01-01', '2010-01-01', '2010-01-01',
               '2010-01-01', '2010-01-01', '2010-01-01', '2010-01-01',
               '2010-01-01', '2010-01-01',
               ...
               '2016-01-01', '2016-01-01', '2016-01-01', '2016-01-01',
               '2016-01-01', '2016-01-01', '2016-01-01', '2016-01-01',
               '2016-01-01', '2016-01-01'],
              dtype='datetime64[ns]', name='Date', length=652, freq=None)

# .set_names()

In [10]:
bigmac = pd.read_csv("bigmac.csv",parse_dates=["Date"],index_col = ["Date","Country"])
bigmac.sort_index(inplace = True)
bigmac.head()

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76
           Britain                   3.67
           Canada                    3.97

In [11]:
bigmac.index.set_names(["Day", "Location"],inplace = True)

In [12]:
bigmac.head(3)

                      Price in US Dollars
Day        Location
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76

In [13]:
bigmac = pd.read_csv("bigmac.csv",parse_dates=["Date"],index_col = ["Date","Country"])
bigmac.sort_index(inplace = True)
bigmac.head()

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76
           Britain                   3.67
           Canada                    3.97

# .sort_index

In [16]:
bigmac.sort_index(ascending = [True, False],inplace=True)
bigmac.head(3)

                          Price in US Dollars
Date       Country
2010-01-01 Uruguay                       3.32
           United States                 3.58
           Ukraine                       1.83

In [15]:
bigmac.sort_index(ascending = [False],inplace=True, level = [0])
bigmac.head()

                          Price in US Dollars
Date       Country
2016-01-01 Vietnam                       2.67
           Venezuela                     0.66
           Uruguay                       3.74
           United States                 4.93
           Ukraine                       1.54

# Extract Rows From a MultiIndex DataFrame

In [68]:
bigmac = pd.read_csv("bigmac.csv",parse_dates=["Date"],index_col = ["Date","Country"])
bigmac.sort_index(inplace = True)
bigmac.head()

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76
           Britain                   3.67
           Canada                    3.97

In [69]:
bigmac.loc[("2010-01-01", "Argentina"), "Price in US Dollars"]

Date        Country
2010-01-01  Argentina    1.84
Name: Price in US Dollars, dtype: float64

In [79]:
bigmac.ix[("2010-01-01", "Argentina"), 0] = 50

In [80]:
bigmac.ix[("2010-01-01", "Argentina"), 0]

50.0

# .transpose() Method

In [81]:
bigmac = pd.read_csv("bigmac.csv",parse_dates=["Date"],index_col = ["Date","Country"])
bigmac.sort_index(inplace = True)
bigmac.head()

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76
           Britain                   3.67
           Canada                    3.97

In [83]:
bigmac = bigmac.transpose()
bigmac.head()

Date                2010-01-01                                              \
Country              Argentina Australia Brazil Britain Canada Chile China
Price in US Dollars       1.84      3.98   4.76    3.67   3.97  3.18  1.83

Date                                                     ...    2016-01-01  \
Country             Colombia Costa Rica Czech Republic   ...   Switzerland
Price in US Dollars     3.91       3.52           3.71   ...          6.44

Date                                                                    \
Country             Taiwan Thailand Turkey   UAE Ukraine United States
Price in US Dollars   2.08     3.09   3.41  3.54    1.54          4.93

Date
Country             Uruguay Venezuela Vietnam
Price in US Dollars    3.74      0.66    2.67

[1 rows x 652 columns]

In [87]:
bigmac.ix["Price in US Dollars",("2016-01-01", "Argentina")]

2.3900000000000001

In [157]:
bigmac = pd.read_csv("bigmac.csv",parse_dates=["Date"],index_col = ["Country"])
bigmac.sort_index(inplace = True)
bigmac.head()

                Date  Price in US Dollars
Country
Argentina 2016-01-01                 2.39
Argentina 2013-07-01                 3.88
Argentina 2015-01-01                 3.25
Argentina 2014-01-01                 3.03
Argentina 2010-07-01                 3.56

In [158]:
bigmac.loc["Argentina"] = bigmac.loc["Argentina"].drop(bigmac.loc["Argentina"].columns[0], axis=1)
bigmac.head()

          Date  Price in US Dollars
Country
Argentina  NaT                 2.39
Argentina  NaT                 3.88
Argentina  NaT                 3.25
Argentina  NaT                 3.03
Argentina  NaT                 3.56

In [159]:
bigmac.loc["Argentina"]

          Date  Price in US Dollars
Country
Argentina  NaT                 2.39
Argentina  NaT                 3.88
Argentina  NaT                 3.25
Argentina  NaT                 3.03
Argentina  NaT                 3.56
Argentina  NaT                 1.84
Argentina  NaT                 3.82
Argentina  NaT                 4.64
Argentina  NaT                 4.16
Argentina  NaT                 4.84
Argentina  NaT                 2.57
Argentina  NaT                 3.07

# .swaplevel()

In [160]:
bigmac = pd.read_csv("bigmac.csv",parse_dates=["Date"],index_col = ["Date","Country"])
bigmac.sort_index(inplace = True)
bigmac.head()

                      Price in US Dollars
Date       Country
2010-01-01 Argentina                 1.84
           Australia                 3.98
           Brazil                    4.76
           Britain                   3.67
           Canada                    3.97

In [164]:
bigmac = bigmac.swaplevel()
bigmac.head(3)

                      Price in US Dollars
Country   Date
Argentina 2010-01-01                 1.84
Australia 2010-01-01                 3.98
Brazil    2010-01-01                 4.76

# .stack() Method

In [169]:
wb= pd.read_csv("worldstats.csv", index_col= ["country","year"])
wb.head(3)

                  Population           GDP
country    year
Arab World 2015  392022276.0  2.530102e+12
           2014  384222592.0  2.873600e+12
           2013  376504253.0  2.846994e+12

In [175]:
wb.stack().to_frame()

                                       0
country    year
Arab World 2015 Population  3.920223e+08
                GDP         2.530102e+12
           2014 Population  3.842226e+08
                GDP         2.873600e+12
           2013 Population  3.765043e+08
                GDP         2.846994e+12
           2012 Population  3.688026e+08
                GDP         2.773270e+12
           2011 Population  3.610318e+08
                GDP         2.497945e+12
           2010 Population  3.531122e+08
                GDP         2.103825e+12
           2009 Population  3.450542e+08
                GDP         1.798878e+12
           2008 Population  3.368865e+08
                GDP         2.081343e+12
           2007 Population  3.287666e+08
                GDP         1.641666e+12
           2006 Population  3.209067e+08
                GDP         1.404190e+12
           2005 Population  3.134309e+08
                GDP         1.184735e+12
           2004 Population  3.063874e+08
                GDP         9.639180e+11
           2003 Population  2.997320e+08
                GDP         8.218702e+11
           2002 Population  2.934026e+08
                GDP         7.279939e+11
           2001 Population  2.872918e+08
                GDP         7.221506e+11
...                                  ...
Zimbabwe   1974 Population  5.967861e+06
                GDP         3.982161e+09
           1973 Population  5.768382e+06
                GDP         3.309354e+09
           1972 Population  5.573312e+06
                GDP         2.677729e+09
           1971 Population  5.385342e+06
                GDP         2.178716e+09
           1970 Population  5.206311e+06
                GDP         1.884206e+09
           1969 Population  5.036321e+06
                GDP         1.747999e+09
           1968 Population  4.874113e+06
                GDP         1.479600e+09
           1967 Population  4.718612e+06
                GDP         1.397002e+09
           1966 Population  4.568320e+06
                GDP         1.281750e+09
           1965 Population  4.422132e+06
                GDP         1.311436e+09
           1964 Population  4.279561e+06
                GDP         1.217138e+09
           1963 Population  4.140804e+06
                GDP         1.159512e+09
           1962 Population  4.006262e+06
                GDP         1.117602e+09
           1961 Population  3.876638e+06
                GDP         1.096647e+09
           1960 Population  3.752390e+06
                GDP         1.052990e+09

[22422 rows x 1 columns]

In [180]:
wb.unstack().unstack().unstack()

country           Afghanistan       Albania       Algeria       Andorra  \
           year
Population 1960  8.994793e+06           NaN  1.112489e+07           NaN
           1961  9.164945e+06           NaN  1.140486e+07           NaN
           1962  9.343772e+06           NaN  1.169015e+07           NaN
           1963  9.531555e+06           NaN  1.198513e+07           NaN
           1964  9.728645e+06           NaN  1.229597e+07           NaN
           1965  9.935358e+06           NaN  1.262695e+07           NaN
           1966  1.014884e+07           NaN  1.298027e+07           NaN
           1967  1.036860e+07           NaN  1.335420e+07           NaN
           1968  1.059979e+07           NaN  1.374438e+07           NaN
           1969  1.084951e+07           NaN  1.414444e+07           NaN
           1970  1.112110e+07           NaN  1.455003e+07  2.427900e+04
           1971  1.141282e+07           NaN  1.496011e+07  2.556000e+04
           1972  1.171690e+07           NaN  1.537710e+07  2.689200e+04
           1973  1.202251e+07           NaN  1.580443e+07  2.823100e+04
           1974  1.231555e+07           NaN  1.624711e+07  2.951400e+04
           1975  1.258295e+07           NaN  1.670910e+07  3.070600e+04
           1976  1.283136e+07           NaN  1.719024e+07  3.178100e+04
           1977  1.305650e+07           NaN  1.769018e+07  3.276900e+04
           1978  1.322255e+07           NaN  1.821233e+07  3.374600e+04
           1979  1.328328e+07           NaN  1.876076e+07  3.481900e+04
           1980  1.321141e+07           NaN  1.933772e+07  3.606300e+04
           1981  1.299692e+07           NaN  1.994367e+07  3.750200e+04
           1982           NaN           NaN  2.057570e+07  3.911200e+04
           1983           NaN           NaN  2.122829e+07  4.086200e+04
           1984           NaN  2.904429e+06  2.189386e+07  4.270400e+04
           1985           NaN  2.964762e+06  2.256591e+07  4.459700e+04
           1986           NaN  3.022635e+06  2.324128e+07  4.651500e+04
           1987           NaN  3.083605e+06  2.391789e+07  4.845800e+04
           1988           NaN  3.142336e+06  2.459149e+07  5.043100e+04
           1989           NaN  3.227943e+06  2.525767e+07  5.244900e+04
...                       ...           ...           ...           ...
GDP        1986           NaN  2.173750e+09  6.369630e+10  4.819962e+08
           1987           NaN  2.156625e+09  6.674227e+10  6.113001e+08
           1988           NaN  2.126000e+09  5.908907e+10  7.214260e+08
           1989           NaN  2.335125e+09  5.563149e+10  7.954895e+08
           1990           NaN  2.101625e+09  6.204510e+10  1.028989e+09
           1991           NaN  1.139167e+09  4.571537e+10  1.106891e+09
           1992           NaN  7.094526e+08  4.800330e+10  1.209993e+09
           1993           NaN  1.228071e+09  4.994646e+10  1.007091e+09
           1994           NaN  1.985674e+09  4.254257e+10  1.017545e+09
           1995           NaN  2.424499e+09  4.176405e+10  1.178745e+09
           1996           NaN  3.314898e+09  4.694150e+10  1.224023e+09
           1997           NaN  2.359903e+09  4.817786e+10  1.180646e+09
           1998           NaN  2.707124e+09  4.818775e+10  1.211954e+09
           1999           NaN  3.414761e+09  4.864061e+10  1.239840e+09
           2000           NaN  3.632044e+09  5.479006e+10  1.401694e+09
           2001  2.461666e+09  4.060759e+09  5.474471e+10  1.484005e+09
           2002  4.128818e+09  4.435079e+09  5.676029e+10  1.717564e+09
           2003  4.583649e+09  5.746946e+09  6.786383e+10  2.373836e+09
           2004  5.285462e+09  7.314865e+09  8.532500e+10  2.916913e+09
           2005  6.275076e+09  8.158549e+09  1.031982e+11  3.248135e+09
           2006  7.057598e+09  8.992642e+09  1.170273e+11  3.536452e+09
           2007  9.843842e+09  1.070101e+10  1.349771e+11  4.010785e+09
           2008  1.019053e+10  1.288135e+10  1.710007e+11  4.001349e+09
           2009  1.248694e+10  1.204421e+10  1.372110e+11  3.649863e+09
           2010  1.593680e+10  1.192695e+10  1.612073e+11  3.346317e+09
           2011  1.793024e+10  1.289087e+10  2.000131e+11  3.427236e+09
           2012  2.053654e+10  1.231978e+10  2.090474e+11  3.146178e+09
           2013  2.004633e+10  1.278103e+10  2.097035e+11  3.249101e+09
           2014  2.005019e+10  1.327796e+10  2.135185e+11           NaN
           2015  1.919944e+10  1.145560e+10  1.668386e+11           NaN

country                Angola  Antigua and Barbuda    Arab World  \
           year
Population 1960           NaN                  NaN           NaN
           1961           NaN                  NaN           NaN
           1962           NaN                  NaN           NaN
           1963           NaN                  NaN           NaN
           1964           NaN                  NaN           NaN
           1965           NaN                  NaN           NaN
           1966           NaN                  NaN           NaN
           1967           NaN                  NaN           NaN
           1968           NaN                  NaN  1.155571e+08
           1969           NaN                  NaN  1.188239e+08
           1970           NaN                  NaN  1.221282e+08
           1971           NaN                  NaN  1.254391e+08
           1972           NaN                  NaN  1.288012e+08
           1973           NaN                  NaN  1.322990e+08
           1974           NaN                  NaN  1.360445e+08
           1975           NaN                  NaN  1.401144e+08
           1976           NaN                  NaN  1.445420e+08
           1977           NaN         7.022300e+04  1.492963e+08
           1978           NaN         7.050800e+04  1.543039e+08
           1979           NaN         7.055300e+04  1.594559e+08
           1980           NaN         7.030100e+04  1.646707e+08
           1981           NaN         6.975000e+04  1.699266e+08
           1982           NaN         6.895000e+04  1.752377e+08
           1983           NaN         6.795800e+04  1.806063e+08
           1984           NaN         6.686300e+04  1.860057e+08
           1985  9.745209e+06         6.574400e+04  1.915643e+08
           1986  1.002370e+07         6.460500e+04  1.972021e+08
           1987  1.028571e+07         6.348400e+04  2.028519e+08
           1988  1.054490e+07         6.253800e+04  2.085463e+08
           1989  1.082099e+07         6.196700e+04  2.142505e+08
...                       ...                  ...           ...
GDP        1986  6.684492e+09         2.458963e+08  2.890606e+11
           1987  6.684492e+09         2.864741e+08  3.129250e+11
           1988  6.684492e+09         3.386963e+08  3.074560e+11
           1989  1.002674e+10         3.734037e+08  3.221911e+11
           1990  1.002741e+10         3.915704e+08  4.460181e+11
           1991  1.451950e+10         4.103889e+08  4.388799e+11
           1992  1.034140e+10         4.237630e+08  4.703749e+11
           1993  1.011215e+10         4.565370e+08  4.756916e+11
           1994  1.042090e+10         5.000889e+08  4.866723e+11
           1995  4.967585e+09         4.941852e+08  5.228684e+11
           1996  7.526964e+09         5.410741e+08  5.773078e+11
           1997  7.649716e+09         5.798519e+08  6.123037e+11
           1998  6.445428e+09         6.200370e+08  5.905141e+11
           1999  6.152937e+09         6.518519e+08  6.431349e+11
           2000  9.129635e+09         7.838379e+08  7.339481e+11
           2001  8.936064e+09         7.737652e+08  7.221506e+11
           2002  1.249735e+10         8.025293e+08  7.279939e+11
           2003  1.418895e+10         8.399964e+08  8.218702e+11
           2004  1.964085e+10         8.983561e+08  9.639180e+11
           2005  2.823371e+10         9.973741e+08  1.184735e+12
           2006  4.178948e+10         1.135144e+09  1.404190e+12
           2007  6.044892e+10         1.289254e+09  1.641666e+12
           2008  8.417803e+10         1.347350e+09  2.081343e+12
           2009  7.549238e+10         1.206410e+09  1.798878e+12
           2010  8.247091e+10         1.135539e+09  2.103825e+12
           2011  1.041159e+11         1.129918e+09  2.497945e+12
           2012  1.153984e+11         1.204713e+09  2.773270e+12
           2013  1.249121e+11         1.200588e+09  2.846994e+12
           2014  1.267751e+11         1.220976e+09  2.873600e+12
           2015  1.026431e+11         1.297285e+09  2.530102e+12

country             Argentina       Armenia         Aruba      ...       \
           year                                                ...
Population 1960           NaN           NaN           NaN      ...
           1961           NaN           NaN           NaN      ...
           1962  2.128768e+07           NaN           NaN      ...
           1963  2.162184e+07           NaN           NaN      ...
           1964  2.195393e+07           NaN           NaN      ...
           1965  2.228339e+07           NaN           NaN      ...
           1966  2.260875e+07           NaN           NaN      ...
           1967  2.293220e+07           NaN           NaN      ...
           1968  2.326127e+07           NaN           NaN      ...
           1969  2.360599e+07           NaN           NaN      ...
           1970  2.397306e+07           NaN           NaN      ...
           1971  2.436644e+07           NaN           NaN      ...
           1972  2.478295e+07           NaN           NaN      ...
           1973  2.521339e+07           NaN           NaN      ...
           1974  2.564450e+07           NaN           NaN      ...
           1975  2.606698e+07           NaN           NaN      ...
           1976  2.647715e+07           NaN           NaN      ...
           1977  2.687857e+07           NaN           NaN      ...
           1978  2.727774e+07           NaN           NaN      ...
           1979  2.768453e+07           NaN           NaN      ...
           1980  2.810589e+07           NaN           NaN      ...
           1981  2.854337e+07           NaN           NaN      ...
           1982  2.899399e+07           NaN           NaN      ...
           1983  2.945474e+07           NaN           NaN      ...
           1984  2.992091e+07           NaN           NaN      ...
           1985  3.038878e+07           NaN           NaN      ...
           1986  3.085724e+07           NaN           NaN      ...
           1987  3.132647e+07           NaN           NaN      ...
           1988  3.179552e+07           NaN           NaN      ...
           1989  3.226356e+07           NaN           NaN      ...
...                       ...           ...           ...      ...
GDP        1986  1.109344e+11           NaN           NaN      ...
           1987  1.111062e+11           NaN           NaN      ...
           1988  1.262068e+11           NaN           NaN      ...
           1989  7.663690e+10           NaN           NaN      ...
           1990  1.413524e+11  2.256839e+09           NaN      ...
           1991  1.897200e+11  2.068527e+09           NaN      ...
           1992  2.287886e+11  1.272578e+09           NaN      ...
           1993  2.367417e+11  1.201313e+09           NaN      ...
           1994  2.574400e+11  1.315159e+09  1.330168e+09      ...
           1995  2.580318e+11  1.468317e+09  1.320670e+09      ...
           1996  2.721498e+11  1.596969e+09  1.379888e+09      ...
           1997  2.928590e+11  1.639492e+09  1.531844e+09      ...
           1998  2.989482e+11  1.893726e+09  1.665363e+09      ...
           1999  2.835230e+11  1.845482e+09  1.722799e+09      ...
           2000  2.842038e+11  1.911564e+09  1.873453e+09      ...
           2001  2.686968e+11  2.118468e+09  1.920263e+09      ...
           2002  9.772451e+10  2.376335e+09  1.941095e+09      ...
           2003  1.275863e+11  2.807061e+09  2.021302e+09      ...
           2004  1.818731e+11  3.576615e+09  2.228279e+09      ...
           2005  2.208138e+11  4.900470e+09  2.331006e+09      ...
           2006  2.626665e+11  6.384452e+09  2.421475e+09      ...
           2007  3.293175e+11  9.206302e+09  2.623726e+09      ...
           2008  4.037820e+11  1.166204e+10  2.791961e+09      ...
           2009  3.766279e+11  8.647937e+09  2.498933e+09      ...
           2010  4.616402e+11  9.260285e+09  2.467704e+09      ...
           2011  5.578902e+11  1.014211e+10  2.584464e+09      ...
           2012  6.043785e+11  1.061932e+10           NaN      ...
           2013  6.239320e+11  1.112147e+10           NaN      ...
           2014  5.480549e+11  1.164444e+10           NaN      ...
           2015           NaN  1.056140e+10           NaN      ...

country            Uzbekistan       Vanuatu  Venezuela, RB       Vietnam  \
           year
Population 1960           NaN           NaN   8.146845e+06           NaN
           1961           NaN           NaN   8.461684e+06           NaN
           1962           NaN           NaN   8.790590e+06           NaN
           1963           NaN           NaN   9.130346e+06           NaN
           1964           NaN           NaN   9.476255e+06           NaN
           1965           NaN           NaN   9.824694e+06           NaN
           1966           NaN           NaN   1.017514e+07           NaN
           1967           NaN           NaN   1.052805e+07           NaN
           1968           NaN           NaN   1.088200e+07           NaN
           1969           NaN           NaN   1.123549e+07           NaN
           1970           NaN           NaN   1.158776e+07           NaN
           1971           NaN           NaN   1.193780e+07           NaN
           1972           NaN           NaN   1.228643e+07           NaN
           1973           NaN           NaN   1.263697e+07           NaN
           1974           NaN           NaN   1.299402e+07           NaN
           1975           NaN           NaN   1.336099e+07           NaN
           1976           NaN           NaN   1.373914e+07           NaN
           1977           NaN           NaN   1.412779e+07           NaN
           1978           NaN           NaN   1.452593e+07           NaN
           1979           NaN  1.125790e+05   1.493174e+07           NaN
           1980           NaN  1.156340e+05   1.534392e+07           NaN
           1981           NaN  1.185780e+05   1.576180e+07           NaN
           1982           NaN  1.214330e+05   1.618590e+07           NaN
           1983           NaN  1.242480e+05   1.661734e+07           NaN
           1984           NaN  1.270940e+05   1.705779e+07           NaN
           1985           NaN  1.300280e+05   1.750806e+07  5.886800e+07
           1986           NaN  1.330400e+05   1.796853e+07  6.024900e+07
           1987           NaN  1.361290e+05   1.843774e+07  6.175000e+07
           1988           NaN  1.393690e+05   1.891243e+07  6.326300e+07
           1989           NaN  1.428520e+05   1.938826e+07  6.477400e+07
...                       ...           ...            ...           ...
GDP        1986           NaN  1.186914e+08   5.891511e+10  2.633662e+10
           1987           NaN  1.308341e+08   4.534379e+10  3.665811e+10
           1988           NaN  1.485454e+08   5.842840e+10  2.542381e+10
           1989           NaN  1.444822e+08   4.214230e+10  6.293305e+09
           1990  1.336061e+10  1.583974e+08   4.702751e+10  6.471740e+09
           1991  1.367762e+10  1.888700e+08   5.173436e+10  9.613370e+09
           1992  1.294130e+10  1.961426e+08   5.847036e+10  9.866990e+09
           1993  1.309901e+10  1.880804e+08   5.810756e+10  1.318095e+10
           1994  1.289916e+10  2.192603e+08   5.652990e+10  1.628643e+10
           1995  1.335047e+10  2.339021e+08   7.488874e+10  2.073616e+10
           1996  1.394889e+10  2.451776e+08   6.825859e+10  2.465747e+10
           1997  1.474460e+10  2.558902e+08   8.583739e+10  2.684370e+10
           1998  1.498897e+10  2.623013e+08   9.133854e+10  2.720960e+10
           1999  1.707847e+10  2.679992e+08   9.797414e+10  2.868366e+10
           2000  1.376037e+10  2.720147e+08   1.171476e+11  3.364009e+10
           2001  1.140135e+10  2.579269e+08   1.229097e+11  3.529135e+10
           2002  9.687951e+09  2.626038e+08   9.288959e+10  3.794790e+10
           2003  1.012811e+10  3.144631e+08   8.362219e+10  4.271707e+10
           2004  1.203002e+10  3.649969e+08   1.124514e+11  4.942411e+10
           2005  1.430751e+10  3.949626e+08   1.455135e+11  5.763326e+10
           2006  1.703090e+10  4.393768e+08   1.834775e+11  6.637166e+10
           2007  2.231139e+10  5.264283e+08   2.303642e+11  7.741443e+10
           2008  2.793403e+10  6.079586e+08   3.156002e+11  9.913030e+10
           2009  3.281683e+10  6.100666e+08   3.294190e+11  1.060146e+11
           2010  3.933277e+10  7.008043e+08   3.938015e+11  1.159317e+11
           2011  4.532432e+10  7.921497e+08   3.164822e+11  1.355395e+11
           2012  5.118344e+10  7.817029e+08   3.812862e+11  1.558200e+11
           2013  5.679566e+10  8.017876e+08   3.713366e+11  1.712220e+11
           2014  6.313285e+10  8.149546e+08            NaN  1.862047e+11
           2015  6.673280e+10           NaN            NaN  1.935994e+11

country          Virgin Islands (U.S.)  West Bank and Gaza         World  \
           year
Population 1960           3.200000e+04                 NaN  3.035056e+09
           1961           3.410000e+04                 NaN  3.076121e+09
           1962           3.630000e+04                 NaN  3.129064e+09
           1963           3.870000e+04                 NaN  3.193947e+09
           1964           4.130000e+04                 NaN  3.259355e+09
           1965           4.400000e+04                 NaN  3.326054e+09
           1966           4.730000e+04                 NaN  3.395866e+09
           1967           5.080000e+04                 NaN  3.465297e+09
           1968           5.460000e+04                 NaN  3.535512e+09
           1969           5.860000e+04                 NaN  3.609910e+09
           1970           6.300000e+04                 NaN  3.684997e+09
           1971           7.100000e+04                 NaN  3.762290e+09
           1972           7.600000e+04                 NaN  3.839016e+09
           1973           8.400000e+04                 NaN  3.914800e+09
           1974           9.000000e+04                 NaN  3.991194e+09
           1975           9.400000e+04                 NaN  4.065955e+09
           1976           9.600000e+04                 NaN  4.138731e+09
           1977           9.300000e+04                 NaN  4.211259e+09
           1978           9.600000e+04                 NaN  4.285062e+09
           1979           9.600000e+04                 NaN  4.360572e+09
           1980           9.700000e+04                 NaN  4.436735e+09
           1981           9.800000e+04                 NaN  4.514656e+09
           1982           1.020000e+05                 NaN  4.595488e+09
           1983           1.040000e+05                 NaN  4.677020e+09
           1984           1.080000e+05                 NaN  4.758310e+09
           1985           1.070000e+05                 NaN  4.841377e+09
           1986           1.065000e+05                 NaN  4.927207e+09
           1987           1.060000e+05                 NaN  5.015268e+09
           1988           1.045000e+05                 NaN  5.104205e+09
           1989           1.030000e+05                 NaN  5.193123e+09
...                                ...                 ...           ...
GDP        1986           1.035600e+09                 NaN  1.499712e+13
           1987           1.147800e+09                 NaN  1.706395e+13
           1988           1.204600e+09                 NaN  1.910918e+13
           1989           1.343900e+09                 NaN  2.006077e+13

In [184]:
wb.unstack(-1)

                          Population                              \
year                            1960          1961          1962
country
Afghanistan             8.994793e+06  9.164945e+06  9.343772e+06
Albania                          NaN           NaN           NaN
Algeria                 1.112489e+07  1.140486e+07  1.169015e+07
Andorra                          NaN           NaN           NaN
Angola                           NaN           NaN           NaN
Antigua and Barbuda              NaN           NaN           NaN
Arab World                       NaN           NaN           NaN
Argentina                        NaN           NaN  2.128768e+07
Armenia                          NaN           NaN           NaN
Aruba                            NaN           NaN           NaN
Australia               1.027648e+07  1.048300e+07  1.074200e+07
Austria                 7.047539e+06  7.086299e+06  7.129864e+06
Azerbaijan                       NaN           NaN           NaN
Bahamas, The            1.095260e+05  1.151080e+05  1.210830e+05
Bahrain                          NaN           NaN           NaN
Bangladesh              4.820070e+07  4.959361e+07  5.103060e+07
Barbados                         NaN           NaN           NaN
Belarus                          NaN           NaN           NaN
Belgium                 9.153489e+06  9.183948e+06  9.220578e+06
Belize                  9.206800e+04  9.470100e+04  9.738900e+04
Benin                   2.431620e+06  2.466002e+06  2.503232e+06
Bermuda                 4.440000e+04  4.550000e+04  4.660000e+04
Bhutan                           NaN           NaN           NaN
Bolivia                 3.693451e+06  3.764815e+06  3.838096e+06
Bosnia and Herzegovina           NaN           NaN           NaN
Botswana                5.240290e+05  5.365760e+05  5.499900e+05
Brazil                  7.249358e+07  7.470689e+07  7.700755e+07
Brunei Darussalam                NaN           NaN           NaN
Bulgaria                         NaN           NaN           NaN
Burkina Faso            4.829291e+06  4.894578e+06  4.960325e+06
...                              ...           ...           ...
Switzerland             5.327827e+06  5.434294e+06  5.573815e+06
Syrian Arab Republic    4.592777e+06  4.742596e+06  4.897428e+06
Tajikistan                       NaN           NaN           NaN
Tanzania                         NaN           NaN           NaN
Thailand                2.739718e+07  2.822421e+07  2.908104e+07
Timor-Leste                      NaN           NaN           NaN
Togo                    1.580513e+06  1.597528e+06  1.612758e+06
Tonga                            NaN           NaN           NaN
Trinidad and Tobago     8.484810e+05  8.653560e+05  8.800190e+05
Tunisia                          NaN           NaN           NaN
Turkey                  2.755328e+07  2.822929e+07  2.890998e+07
Turkmenistan                     NaN           NaN           NaN
Tuvalu                           NaN           NaN           NaN
Uganda                  6.788211e+06  7.006629e+06  7.240155e+06
Ukraine                          NaN           NaN           NaN
United Arab Emirates             NaN           NaN           NaN
United Kingdom          5.240000e+07  5.280000e+07  5.325000e+07
United States           1.806710e+08  1.836910e+08  1.865380e+08
Upper middle income     1.154592e+09  1.159145e+09  1.176093e+09
Uruguay                 2.538651e+06  2.571691e+06  2.603887e+06
Uzbekistan                       NaN           NaN           NaN
Vanuatu                          NaN           NaN           NaN
Venezuela, RB           8.146845e+06  8.461684e+06  8.790590e+06
Vietnam                          NaN           NaN           NaN
Virgin Islands (U.S.)   3.200000e+04  3.410000e+04  3.630000e+04
West Bank and Gaza               NaN           NaN           NaN
World                   3.035056e+09  3.076121e+09  3.129064e+09
Yemen, Rep.                      NaN           NaN           NaN
Zambia                  3.049586e+06  3.142848e+06  3.240664e+06
Zimbabwe                3.752390e+06  3.876638e+06  4.006262e+06

                                                                  \
year                            1963          1964          1965
country
Afghanistan             9.531555e+06  9.728645e+06  9.935358e+06
Albania                          NaN           NaN           NaN
Algeria                 1.198513e+07  1.229597e+07  1.262695e+07
Andorra                          NaN           NaN           NaN
Angola                           NaN           NaN           NaN
Antigua and Barbuda              NaN           NaN           NaN
Arab World                       NaN           NaN           NaN
Argentina               2.162184e+07  2.195393e+07  2.228339e+07
Armenia                          NaN           NaN           NaN
Aruba                            NaN           NaN           NaN
Australia               1.095000e+07  1.116700e+07  1.138800e+07
Austria                 7.175811e+06  7.223801e+06  7.270889e+06
Azerbaijan                       NaN           NaN           NaN
Bahamas, The            1.273310e+05  1.336970e+05  1.400490e+05
Bahrain                          NaN           NaN           NaN
Bangladesh              5.253260e+07  5.412939e+07  5.583502e+07
Barbados                         NaN           NaN           NaN
Belarus                          NaN           NaN           NaN
Belgium                 9.289770e+06  9.378113e+06  9.463667e+06
Belize                  1.001660e+05  1.030700e+05  1.061210e+05
Benin                   2.543335e+06  2.586362e+06  2.632360e+06
Bermuda                 4.770000e+04  4.890000e+04  5.010000e+04
Bhutan                           NaN           NaN           NaN
Bolivia                 3.913397e+06  3.990855e+06  4.070590e+06
Bosnia and Herzegovina           NaN           NaN           NaN
Botswana                5.643160e+05  5.795600e+05  5.957410e+05
Brazil                  7.936845e+07  8.175180e+07  8.413006e+07
Brunei Darussalam                NaN           NaN  1.025250e+05
Bulgaria                         NaN           NaN           NaN
Burkina Faso            5.027818e+06  5.098892e+06  5.174869e+06
...                              ...           ...           ...
Switzerland             5.694247e+06  5.789228e+06  5.856472e+06
Syrian Arab Republic    5.057825e+06  5.224579e+06  5.398333e+06
Tajikistan                       NaN           NaN           NaN
Tanzania                         NaN           NaN           NaN
Thailand                2.996704e+07  3.088133e+07  3.182280e+07
Timor-Leste                      NaN           NaN           NaN
Togo                    1.631763e+06  1.662072e+06  1.708632e+06
Tonga                            NaN           NaN           NaN
Trinidad and Tobago     8.925710e+05  9.032720e+05  9.124190e+05
Tunisia                          NaN           NaN  4.630000e+06
Turkey                  2.959705e+07  3.029297e+07  3.100017e+07
Turkmenistan                     NaN           NaN           NaN
Tuvalu                           NaN           NaN           NaN
Uganda                  7.487411e+06  7.746181e+06  8.014376e+06
Ukraine                          NaN           NaN           NaN
United Arab Emirates             NaN           NaN           NaN
United Kingdom          5.365000e+07  5.400000e+07  5.434805e+07
United States           1.892420e+08  1.918890e+08  1.943030e+08
Upper middle income     1.204372e+09  1.232266e+09  1.261069e+09
Uruguay                 2.635128e+06  2.665387e+06  2.694535e+06
Uzbekistan                       NaN           NaN           NaN
Vanuatu                          NaN           NaN           NaN
Venezuela, RB           9.130346e+06  9.476255e+06  9.824694e+06
Vietnam                          NaN           NaN           NaN
Virgin Islands (U.S.)   3.870000e+04  4.130000e+04  4.400000e+04
West Bank and Gaza               NaN           NaN           NaN
World                   3.193947e+09  3.259355e+09  3.326054e+09
Yemen, Rep.                      NaN           NaN           NaN
Zambia                  3.342894e+06  3.449266e+06  3.559687e+06
Zimbabwe                4.140804e+06  4.279561e+06  4.422132e+06

                                                                  \
year                            1966          1967          1968
country
Afghanistan             1.014884e+07  1.036860e+07  1.059979e+07
Albania                          NaN           NaN           NaN
Algeria                 1.298027e+07  1.335420e+07  1.374438e+07
Andorra                          NaN           NaN           NaN
Angola                           NaN           NaN           NaN
Antigua and Barbuda              NaN           NaN           NaN
Arab World                       NaN           NaN  1.155571e+08
Argentina               2.260875e+07  2.293220e+07  2.326127e+07
Armenia                          NaN           NaN           NaN
Aruba                            NaN           NaN           NaN
Australia               1.165100e+07  1.179900e+07  1.200900e+07
Austria                 7.322066e+06  7.376998e+06  7.415403e+06
Azerbaijan                       NaN           NaN           NaN
Bahamas, The            1.463640e+05  1.526070e+05  1.586290e+05
Bahrain                          NaN           NaN           NaN
Bangladesh              5.767553e+07  5.962529e+07  6.158552e+07
Barbados                         NaN           NaN           NaN
Belarus                          NaN           NaN           NaN
Belgium                 9.527807e+06  9.580991e+06  9.618756e+06
Belize                  1.093440e+05  1.126990e+05  1.160610e+05
Benin                   2.681382e+06  2.733450e+06  2.788551e+06
Bermuda                 5.100000e+04  5.200000e+04  5.300000e+04
Bhutan                           NaN           NaN           NaN
Bolivia                 4.152665e+06  4.237126e+06  4.324066e+06
Bosnia and Herzegovina           NaN           NaN           NaN
Botswana                6.129500e+05  6.312760e+05  6.507300e+05
Brazil                  8.649499e+07  8.885368e+07  9.121301e+07
Brunei Darussalam       1.074500e+05  1.126800e+05  1.181760e+05
Bulgaria                         NaN           NaN           NaN
Burkina Faso            5.256363e+06  5.343020e+06  5.434040e+06
...                              ...           ...           ...
Switzerland             5.918002e+06  5.991785e+06  6.067714e+06
Syrian Arab Republic    5.579283e+06  5.767478e+06  5.963248e+06
Tajikistan                       NaN           NaN           NaN
Tanzania                         NaN           NaN           NaN
Thailand                3.278910e+07  3.377850e+07  3.479094e+07
Timor-Leste                      NaN           NaN           NaN
Togo                    1.774029e+06  1.855445e+06  1.945781e+06
Tonga                            NaN           NaN           NaN
Trinidad and Tobago     9.199020e+05  9.259180e+05  9.314660e+05
Tunisia                 4.731395e+06  4.832923e+06  4.933131e+06
Turkey                  3.171827e+07  3.244840e+07  3.319629e+07
Turkmenistan                     NaN           NaN           NaN
Tuvalu                           NaN           NaN           NaN
Uganda                  8.292747e+06  8.580632e+06  8.872866e+06
Ukraine                          NaN           NaN           NaN
United Arab Emirates             NaN           NaN           NaN
United Kingdom          5.464850e+07  5.494360e+07  5.521170e+07
United States           1.965600e+08  1.987120e+08  2.007060e+08
Upper middle income     1.292755e+09  1.323615e+09  1.355381e+09
Uruguay                 2.722874e+06  2.750093e+06  2.774771e+06
Uzbekistan                       NaN           NaN           NaN
Vanuatu                          NaN           NaN           NaN
Venezuela, RB           1.017514e+07  1.052805e+07  1.088200e+07
Vietnam                          NaN           NaN           NaN
Virgin Islands (U.S.)   4.730000e+04  5.080000e+04  5.460000e+04
West Bank and Gaza               NaN           NaN           NaN
World                   3.395866e+09  3.465297e+09  3.535512e+09
Yemen, Rep.                      NaN           NaN           NaN
Zambia                  3.674088e+06  3.792864e+06  3.916928e+06
Zimbabwe                4.568320e+06  4.718612e+06  4.874113e+06

                                          ...                GDP  \
year                            1969      ...               2006
country                                   ...
Afghanistan             1.084951e+07      ...       7.057598e+09
Albania                          NaN      ...       8.992642e+09
Algeria                 1.414444e+07      ...       1.170273e+11
Andorra                          NaN      ...       3.536452e+09
Angola                           NaN      ...       4.178948e+10
Antigua and Barbuda              NaN      ...       1.135144e+09
Arab World              1.188239e+08      ...       1.404190e+12
Argentina               2.360599e+07      ...       2.626665e+11
Armenia                          NaN      ...       6.384452e+09
Aruba                            NaN      ...       2.421475e+09
Australia               1.226300e+07      ...       7.468808e+11
Austria                 7.441055e+06      ...       3.343094e+11
Azerbaijan                       NaN      ...       2.098302e+10
Bahamas, The            1.642500e+05      ...       7.965588e+09
Bahrain                          NaN      ...       1.850505e+10
Bangladesh              6.342257e+07      ...       7.181908e+10
Barbados                         NaN      ...       4.303500e+09
Belarus                          NaN      ...       3.696182e+10
Belgium                 9.646032e+06      ...       4.098131e+11
Belize                  1.192600e+05      ...       1.217442e+09
Benin                   2.846652e+06      ...       5.142381e+09
Bermuda                 5.400000e+04      ...       5.414299e+09
Bhutan                           NaN      ...       8.977315e+08
Bolivia                 4.413584e+06      ...       1.145187e+10
Bosnia and Herzegovina           NaN      ...       1.286652e+10
Botswana                6.713050e+05      ...       1.012694e+10
Brazil                  9.358575e+07      ...       1.107640e+12
Brunei Darussalam       1.238750e+05      ...       1.147070e+10
Bulgaria                         NaN      ...       3.430445e+10
Burkina Faso            5.528172e+06      ...       5.844670e+09
...                              ...      ...                ...
Switzerland             6.136387e+06      ...       4.291956e+11
Syrian Arab Republic    6.166933e+06      ...       3.333284e+10
Tajikistan                       NaN      ...       2.830229e+09
Tanzania                         NaN      ...       1.861046e+10
Thailand                3.582680e+07      ...       2.217585e+11
Timor-Leste                      NaN      ...       4.630000e+08
Togo                    2.034909e+06      ...       2.202809e+09
Tonga                            NaN      ...       2.879830e+08
Trinidad and Tobago     9.378460e+05      ...       1.836907e+10
Tunisia                 5.031211e+06      ...       3.437844e+10
Turkey                  3.396920e+07      ...       5.309001e+11
Turkmenistan                     NaN      ...       1.027760e+10
Tuvalu                           NaN      ...       2.290286e+07
Uganda                  9.162773e+06      ...       9.942598e+09
Ukraine                          NaN      ...       1.077531e+11
United Arab Emirates             NaN      ...       2.221059e+11
United Kingdom          5.544175e+07      ...       2.588077e+12
United States           2.026770e+08      ...       1.385589e+13
Upper middle income     1.388827e+09      ...       8.620784e+12
Uruguay                 2.795044e+06      ...       1.957946e+10
Uzbekistan                       NaN      ...       1.703090e+10
Vanuatu                          NaN      ...       4.393768e+08
Venezuela, RB           1.123549e+07      ...       1.834775e+11
Vietnam                          NaN      ...       6.637166e+10
Virgin Islands (U.S.)   5.860000e+04      ...                NaN
West Bank and Gaza               NaN      ...       4.910100e+09
World                   3.609910e+09      ...       5.107451e+13
Yemen, Rep.                      NaN      ...       1.908173e+10
Zambia                  4.047479e+06      ...       1.275686e+10
Zimbabwe                5.036321e+06      ...       5.443896e+09

                                                                  \
year                            2007          2008          2009
country
Afghanistan             9.843842e+09  1.019053e+10  1.248694e+10
Albania                 1.070101e+10  1.288135e+10  1.204421e+10
Algeria                 1.349771e+11  1.710007e+11  1.372110e+11
Andorra                 4.010785e+09  4.001349e+09  3.649863e+09
Angola                  6.044892e+10  8.417803e+10  7.549238e+10
Antigua and Barbuda     1.289254e+09  1.347350e+09  1.206410e+09
Arab World              1.641666e+12  2.081343e+12  1.798878e+12
Argentina               3.293175e+11  4.037820e+11  3.766279e+11
Armenia                 9.206302e+09  1.166204e+10  8.647937e+09
Aruba                   2.623726e+09  2.791961e+09  2.498933e+09
Australia               8.530533e+11  1.054558e+12  9.265638e+11
Austria                 3.864590e+11  4.276115e+11  3.975943e+11
Azerbaijan              3.305034e+10  4.885248e+10  4.429149e+10
Bahamas, The            8.318996e+09  8.246650e+09  7.820420e+09
Bahrain                 2.173000e+10  2.571088e+10  2.293822e+10
Bangladesh              7.961189e+10  9.163128e+10  1.024778e+11
Barbados                4.546000e+09  4.595000e+09  4.602000e+09
Belarus                 4.527575e+10  6.075218e+10  4.920866e+10
Belgium                 4.718218e+11  5.186260e+11  4.845527e+11
Belize                  1.290543e+09  1.368625e+09  1.336957e+09
Benin                   5.969535e+09  7.132787e+09  7.097199e+09
Bermuda                 5.895048e+09  6.109928e+09  5.806378e+09
Bhutan                  1.196092e+09  1.258332e+09  1.264758e+09
Bolivia                 1.312018e+10  1.667432e+10  1.733999e+10
Bosnia and Herzegovina  1.577642e+10  1.910145e+10  1.760063e+10
Botswana                1.093905e+10  1.094507e+10  1.026713e+10
Brazil                  1.397084e+12  1.695825e+12  1.667020e+12
Brunei Darussalam       1.224769e+10  1.439310e+10  1.073237e+10
Bulgaria                4.476573e+10  5.466664e+10  5.178345e+10
Burkina Faso            6.771278e+09  8.369637e+09  8.369175e+09
...                              ...           ...           ...
Switzerland             4.774078e+11  5.515470e+11  5.395282e+11
Syrian Arab Republic    4.040501e+10           NaN           NaN
Tajikistan              3.719515e+09  5.161299e+09  4.979472e+09
Tanzania                2.150174e+10  2.736839e+10  2.857378e+10
Thailand                2.629427e+11  2.913831e+11  2.815748e+11
Timor-Leste             5.590000e+08  6.940000e+08  8.180000e+08
Togo                    2.523463e+09  3.163416e+09  3.163001e+09
Tonga                   2.996579e+08  3.400415e+08  3.213034e+08
Trinidad and Tobago     2.164230e+10  2.787026e+10  1.917520e+10
Tunisia                 3.890807e+10  4.485659e+10  4.345494e+10
Turkey                  6.471551e+11  7.303375e+11  6.145539e+11
Turkmenistan            1.266417e+10  1.927152e+10  2.021439e+10
Tuvalu                  2.703037e+07  3.029022e+07  2.710108e+07
Uganda                  1.229281e+10  1.423903e+10  1.787818e+10
Ukraine                 1.427190e+11  1.799924e+11  1.172278e+11
United Arab Emirates    2.579161e+11  3.154746e+11  2.535474e+11
United Kingdom          2.969734e+12  2.793377e+12  2.314577e+12
United States           1.447764e+13  1.471858e+13  1.441874e+13
Upper middle income     1.073130e+13  1.312644e+13  1.263584e+13
Uruguay                 2.341057e+10  3.036621e+10  3.166091e+10
Uzbekistan              2.231139e+10  2.793403e+10  3.281683e+10